// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtIuxQxN81JiXk6ffQOiEjS0fwHep0RV4',
    appId: '1:185841650823:web:f2e7d20651919cf4843c22',
    messagingSenderId: '185841650823',
    projectId: 'omp-app-a406c',
    authDomain: 'omp-app-a406c.firebaseapp.com',
    storageBucket: 'omp-app-a406c.appspot.com',
    measurementId: 'G-042DNGL1GF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYmiJI9PavLL_OGkqLDch6nwZt891kimg',
    appId: '1:185841650823:android:66ab78f430baf994843c22',
    messagingSenderId: '185841650823',
    projectId: 'omp-app-a406c',
    storageBucket: 'omp-app-a406c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIs3c9WooY40zwSTgAzLEIEYnqHgflTSk',
    appId: '1:185841650823:ios:08ea3123194b5b14843c22',
    messagingSenderId: '185841650823',
    projectId: 'omp-app-a406c',
    storageBucket: 'omp-app-a406c.appspot.com',
    iosClientId: '185841650823-0jpr81emjscrnbsqoohobo9eaavei21q.apps.googleusercontent.com',
    iosBundleId: 'com.example.ompApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIs3c9WooY40zwSTgAzLEIEYnqHgflTSk',
    appId: '1:185841650823:ios:08ea3123194b5b14843c22',
    messagingSenderId: '185841650823',
    projectId: 'omp-app-a406c',
    storageBucket: 'omp-app-a406c.appspot.com',
    iosClientId: '185841650823-0jpr81emjscrnbsqoohobo9eaavei21q.apps.googleusercontent.com',
    iosBundleId: 'com.example.ompApp',
  );
}
